// app/control-panel/src/layout/Header.jsx
import React from "react";
import AppBar from "@mui/material/AppBar";
import Toolbar from "@mui/material/Toolbar";
import Typography from "@mui/material/Typography";
import Box from "@mui/material/Box";import logo from '../recources/logo.png';

export default function Header() {
    return (
        <AppBar position="static" sx={{ 
            backgroundColor: '#8fbc8f', 
            color: 'common.white' }}>
            <Toolbar>
                <Box
                    component="img"
                    src={logo}
                    alt="Logo"
                    sx={{
                        height: 40,
                        width: "auto",
                        mr: 2,
                    }}
                />

                <Typography variant="h6" sx={{ flexGrow: 1 }}>
                   Plant Monitoring Dashboard
                </Typography>

            </Toolbar>
        </AppBar>
    );
}

// frontend/src/app/layout/header/header-component.component.ts
import { Component } from '@angular/core';
import {MatToolbar} from '@angular/material/toolbar';
import {NgOptimizedImage} from '@angular/common';

@Component({
  selector: 'app-header',
  templateUrl: './header-component.component.html',
  styleUrl: './header-component.component.css',
  imports: [
    MatToolbar,
    NgOptimizedImage
  ]
})
export class HeaderComponent {}

<mat-toolbar color="primary" class="header">
  <img ngSrc="/assets/logo.png" alt="Logo" class="logo" height="90" width="90">
  <span class="title">Plant Monitoring Dashboard</span>
</mat-toolbar>
