// frontend/src/app/component/plant-info/plant-info-card-component.component.ts
import { Component } from '@angular/core';

import {MatFormField, MatInput, MatLabel} from '@angular/material/input';
import {MatCard, MatCardContent} from '@angular/material/card';
import {MatButton} from '@angular/material/button';
import {FormsModule} from '@angular/forms';

@Component({
  selector: 'app-plant-info-card-component',
  templateUrl: './plant-info-card-component.component.html',
  imports: [
    MatCard,
    MatCardContent,
    MatFormField,
    MatLabel,
    MatButton,
    MatInput,
    FormsModule,
  ],
  styleUrls: ['./plant-info-card-component.component.css']
})
export class PlantInfoCardComponent {
  isEditable = false;
  plantData = {
    name: 'Ficus',
    species: 'Ficus elastica',
    wateringSchedule: 'Once a week'
  };

  handleEditToggle() {
    this.isEditable = !this.isEditable;
  }

  handleChange(event: Event) {
    const input = event.target as HTMLInputElement;
    const { name, value } = input;
    this.plantData = {
      ...this.plantData,
      [name]: value
    };
  }
}

<mat-card style="width: 80%; margin: 30px auto;">
  <mat-card-content>
    <h2>Plant Information</h2>
    <div class="grid-container">
      <mat-form-field appearance="fill" class="full-width">
        <mat-label>Plant Name</mat-label>
        <input matInput name="name" [(ngModel)]="plantData.name" [disabled]="!isEditable">
      </mat-form-field>
      <mat-form-field appearance="fill" class="full-width">
        <mat-label>Species</mat-label>
        <input matInput name="species" [(ngModel)]="plantData.species" [disabled]="!isEditable">
      </mat-form-field>
      <mat-form-field appearance="fill" class="full-width">
        <mat-label>Watering Schedule</mat-label>
        <input matInput name="wateringSchedule" [(ngModel)]="plantData.wateringSchedule" [disabled]="!isEditable">
      </mat-form-field>
    </div>
    <button mat-raised-button color="primary" (click)="handleEditToggle()" style="margin-top: 20px;">
      {{ isEditable ? 'Save' : 'Edit' }}
    </button>
  </mat-card-content>
</mat-card>

// app/control-panel/src/component/PlantInfoCard.jsx
import React, { useState } from 'react';
import { Card, CardContent, Button, Typography, TextField, Grid } from '@mui/material';



const PlantInfoCard = () => {
  const [isEditable, setIsEditable] = useState(false);
  const [plantData, setPlantData] = useState({
    name: 'Ficus',
    species: 'Ficus elastica',
    wateringSchedule: 'Once a week'
  });

  const handleEditToggle = () => {
    setIsEditable(!isEditable);
  };

  const handleChange = (e) => {
    const { name, value } = e.target;
    setPlantData((prevData) => ({
      ...prevData,
      [name]: value,
    }));
  };

  return (
    <Card style={{ width: '80%', margin: '30px auto' }}>
      <CardContent>
        <Typography variant="h5" gutterBottom>
          Plant Information
        </Typography>
        <Grid container spacing={2} direction={'column'}>
          <Grid item xs={12}>
            <TextField
              label="Plant Name"
              name="name"
              value={plantData.name}
              onChange={handleChange}
              disabled={!isEditable}
              fullWidth
            />
          </Grid>
          <Grid item xs={12}>
            <TextField
              label="Species"
              name="species"
              value={plantData.species}
              onChange={handleChange}
              disabled={!isEditable}
              fullWidth
            />
          </Grid>
          <Grid item xs={12}>
            <TextField
              label="Watering Schedule"
              name="wateringSchedule"
              value={plantData.wateringSchedule}
              onChange={handleChange}
              disabled={!isEditable}
              fullWidth
            />
          </Grid>
        
        </Grid>
        <Button
          variant="contained"
          color="primary"
          onClick={handleEditToggle}
          style={{ marginTop: '20px' }}
        >
          {isEditable ? 'Save' : 'Edit'}
        </Button>
      </CardContent>
    </Card>
  );
};

export default PlantInfoCard;
